baseURL = "https://www.strategyxdesign.co.uk/"
languageCode = "en-us"
title = "Strategy x Design"

[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.91.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

theme = "hugo-kiera"

    [params]
    subtitle = "Strategic Design Practice"
    tagline = "Tom Eldridge, designs, builds, and writes"
    description = "Kiera: A Hugo theme for creative and technical writing."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    homepageLength = 10
    google_fonts = ["Spectral"] # Adds additional google fonts
    